# .github/workflows/update-data.yaml - Direct commits for data
name: Update 3. Liga Data

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Chrome (for Selenium)
      run: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run data collection pipeline
      run: |
        python main.py run
        
    - name: Commit and push data updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "3. Liga Data Bot"
        
        # Only commit if there are changes
        if [[ -n $(git status --porcelain) ]]; then
          git add data/
          git commit -m "🤖 Auto-update 3. Liga data $(date '+%Y-%m-%d %H:%M UTC')"
          git push
          echo "✅ Data updated and pushed"
        else
          echo "ℹ️ No data changes detected"
        fi